### ISSUE TITLE
Feature idea : Close when clicking the overlay or pressing esc key

### ISSUE THREAD

**Issue by kaelig** [plasm/simplemodal#1]

**Comment by plasm** [comment]
yeah
thanks

**Comment by webdokkeren** [comment]
Would be really nice to see those two features in simplemodal. Would make it an even more awesome plugin :-)

**Comment by HTMLGuyLLC** [comment]
Want close when clicking overlay or ESC? Try jAlert http://flwebsites.biz/jAlert/
