### ISSUE TITLE
Use &times; as close button instead of letter X

### ISSUE THREAD

**Issue by Serhii-DV** [plasm/simplemodal#10]
Hi.

Please, just see this image example:

![](http://gyazo.com/f10a409dbe55cb38c47d42ea0ae717c2.png)

I make `font-size: 22px`

Besides, `&times;` is used in Twitter Bootstrap.

**Comment by xchs** [comment]
_**+1**_ &ndash; I like it!

Would also replace the font weight from `normal` to `bold` to emphasize this close button a little bit more:

``` css
font-weight: bold;
```

**Comment by sebackend** [comment]
I like the Heavy Multiplication x
![heavy_multiplication_x](https://cloud.githubusercontent.com/assets/14254060/9934377/34d73da0-5d27-11e5-8add-7bf755cfa4ba.png)

using <pre>& #10006;</pre>

**Comment by vergissberlin** [comment]
# ×

Or better use the smaller one:

http://www.fileformat.info/info/unicode/char/2a2f/index.htm

```
&#10799;
```
