### ISSUE TITLE
jQuery Alternative

### ISSUE THREAD

**Issue by adyz** [plasm/simplemodal#11]
Hello, 

This is not an actual issue, so sorry about posting here, but I can't find any other place.

I love the way this modal looks and acts, but I don't know MooTools and I also used jQuery on this page that I want to include your modal.

Is is that hard to convert this into a jQuery modal?

Did anybody suggested that before? I think so!

This will be allot more used if it was jQuery based.

Any arguments why can't be done with jQuery?

If none, maybe I will try to convert-it! 

Great design guys!

Thank, 
Adrian

**Comment by msm2020** [comment]
hello, i have same problem, any help please
