### ISSUE TITLE
You need to state that this library needs Mootools 

### ISSUE THREAD

**Issue by nhc** [plasm/simplemodal#5]
No where does it mention that Mootools is required. You must state the dependencies.

**Comment by plasm** [comment]
.....
simple-modal.js

rows 17/22
- Mootools Simple Modal
- Version 1.0
- Copyright (c) 2011 Marco Dell'Anna - http://www.plasm.it
  *
- Requires:
- MooTools http://mootools.net

bye

Neil Charlton  
reply@reply.github.com ha  
scritto:

**Comment by adyz** [comment]
Hi, 

Do you think will slow down my page to much if I already have half of functionality based on jQuery and now I need to add MooTools also?

Thanks, 
Adrian

**Comment by plasm** [comment]
hi,

add Mootool and JQ is never a good solution. If you use JQ ... JQ uses.
There is a version of MS JQ, I have never experienced how true but it exists.

https://github.com/mbuczko/simplemodal-jquery

Il giorno 28/giu/2012, alle ore 20:00, Florescu Adrian ha scritto:

> Hi, 
> 
> Do you think will slow down my page to much if I already have half of functionality based on jQuery and now I need to add MooTools also?
> 
> Thanks, 
> Adrian

**Comment by adyz** [comment]
Ow, Thanks!!!!

**Comment by plasm** [comment]
:)

Il giorno 28/giu/2012, alle ore 20:19, Florescu Adrian ha scritto:
